development:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
test:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
production:
  server: "http://example.com/faye"
  secret_token: "01e4fe68aa70b212a754ef1c456e80f093fc72a52af91ef9997db60a8d660525"
  signature_expiration: 3600 # one hour
