# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 92335620062064454136cec47e50ca45415564bddbbb16d1e16ca1e479c9052bc5dc1390ddcac9673aaf6a8a32e598283ad6873e49ef60b6117f93804846076e

test:
  secret_key_base: 3182d2bf117208e2a06108e6a8fb2e5101c644ff5e909ec6e2fdc11c2e65a2316bea0e36de79e236e2f9a37e2e6b619ea83e9002074f74f08ebf92408d8a1362

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
